import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { headers } from 'next/headers'

import { Web3Modal } from '@/context/Web3Modal'
import { cookieToInitialState } from 'wagmi'
import { wagmiConfig } from '@/context/wagmiConfig'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface Props {
  children: React.ReactNode
}

export default async function RootLayout({ children }: Props) {
	const initialState = cookieToInitialState(
    wagmiConfig, 
    headers().get('cookie')
  )
	return (
		<html lang="en">
			<body className={inter.className}>
				<Web3Modal initialState={initialState} >{children}</Web3Modal>
			</body>
		</html>
	)
}
